name: feelosphere
favicon: null
layout_spectrum: 0.7175618312321603
typography_spectrum: 0.680508287390694
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5441754136700183
  lightness: 0.6479438683018088
  saturation: 0.3990169852040708
  rhythmicContrast: 0.18567415210418403
purpose: []
